budget_alert_check_job:
  cron: '0 8,20 * * *'  # Twice daily at 8 AM and 8 PM
  class: BudgetAlertCheckJob
  description: "Check budgets for potential alerts"

goal_milestone_check_job:
  cron: '0 9 * * *'  # Daily at 9 AM
  class: GoalMilestoneCheckJob
  description: "Check goal milestones for notifications"

recurring_transaction_reminder_job:
  cron: '0 7 * * *'  # Daily at 7 AM
  class: RecurringTransactionReminderJob
  description: "Send reminders for upcoming recurring transactions"

monthly_summary_job:
  cron: '0 8 1 * *'  # At 8 AM on the 1st of every month
  class: MonthlySummaryJob
  description: "Generate monthly financial summaries"
